alphabet_error = 'O alfabeto deve ter no máximo 5 caracteres.'
states_error = 'Deve haver no máximo 10 estados.'
less_than_1_transitions_error = 'Deve haver no mínimo 1 transição.'
bigger_than_100_transitions_error = 'Deve haver no máximo 100 transições.'
initial_state_error = 'O estado inicial deve fazer parte de um estado existente.'
final_state_error = 'Deve haver no máximo 10 estados finais.'
